import type { PayMuxServerConfig } from '../types.js';
import type { ChargeOptions } from '../../shared/types.js';
import { generateX402Requirements } from '../protocols/x402.js';

/**
 * Build payment requirements for all configured protocols.
 *
 * x402 uses the PAYMENT-REQUIRED header (base64 JSON).
 * MPP uses the WWW-Authenticate: Payment header (challenge params).
 * Both can be present simultaneously when the server accepts both protocols.
 */
export function buildPaymentRequirements(
  config: PayMuxServerConfig,
  chargeOpts: ChargeOptions,
  resource: string
): {
  paymentRequired: string | null;
  wwwAuthenticate: string | null;
  body: Record<string, unknown>;
} {
  let paymentRequired: string | null = null;
  let wwwAuthenticate: string | null = null;
  const body: Record<string, unknown> = {};

  // x402: PAYMENT-REQUIRED header with base64-encoded JSON
  if (config.accept.includes('x402') && config.x402) {
    paymentRequired = generateX402Requirements(config, chargeOpts, resource);
    body.x402 = JSON.parse(atob(paymentRequired));
  }

  // MPP: WWW-Authenticate header is generated by mppx at request time,
  // not at build-requirements time (because it requires HMAC signing).
  // We signal that MPP is available so the middleware adds the challenge
  // via handleMppRequest() which delegates to mppx.charge().
  if (config.accept.includes('mpp') && config.mpp) {
    // The actual WWW-Authenticate: Payment header will be generated by
    // mppx.charge()(request) when it returns { status: 402, challenge }.
    // We can't pre-generate it here because it needs to be bound to the
    // specific request via HMAC. Instead, the middleware will call
    // handleMppRequest() to get the challenge response.
    //
    // For the initial "no payment" case, we let the middleware handle MPP
    // challenge generation by passing the request to mppx. Here we just
    // note that MPP is available.
    body.mpp = { available: true, method: 'tempo' };
  }

  return { paymentRequired, wwwAuthenticate, body };
}
